name: code_check

on:
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install packages
        yarn install
      - name: Formatter
        yarn format
      - name: Lint
        yarn lint
